tsbin/mlnx_bf_configure: Added timeout on rdma system set netns command
rdma system set netns exclusive - might fail with the following error:
error: Device or resource busy

Retry rdma command till the timeout expires

Issue: 3563579
Signed-off-by: Vladimir Sokolovsky <vlad@nvidia.com>
(cherry picked from commit 5dedf61d4561750613ddf0342ce078b14eb577dd)